    -- Delete the contents of all analysis tables
    DELETE FROM analysis_tables.analysis;
    DELETE FROM analysis_tables.amino_acids;
    DELETE FROM analysis_tables.analysis_certified_materials;
    DELETE FROM analysis_tables.analysis_measures;
    DELETE FROM analysis_tables.contaminants_dioxin;
    DELETE FROM analysis_tables.contaminants_hg;
    DELETE FROM analysis_tables.contaminants_musk;
    DELETE FROM analysis_tables.contaminants_pcb;
    DELETE FROM analysis_tables.contaminants_tm;
    DELETE FROM analysis_tables.fatmeter;
    DELETE FROM analysis_tables.fatty_acids;
    DELETE FROM analysis_tables.grinding_details;
    DELETE FROM analysis_tables.lipid_classes;
    DELETE FROM analysis_tables.lipids_extraction_details;
    DELETE FROM analysis_tables.otoliths_increment_counts;
    DELETE FROM analysis_tables.otoliths_morphometry;
    DELETE FROM analysis_tables.proteins;
    DELETE FROM analysis_tables.reproduction;
    DELETE FROM analysis_tables.stable_isotopes;

    -- Empty the full database

    -- Delete samples
    DELETE FROM public.sample_bank;
    DELETE FROM public.samples_origin;
    DELETE FROM public.sample_dryed_bank;
    DELETE FROM public.sample_grinded_bank;

    -- Delete fish
    DELETE FROM public.fish;
    DELETE FROM public.fish_measures;
    DELETE FROM public.fish_caught;
    DELETE FROM public.fishing_environment;

    -- Delete metadata
    DELETE FROM metadata.analysis_tracers_details;
    DELETE FROM metadata.fish_measures_details;
    DELETE FROM metadata.ddd;

    -- Delete references
    DELETE FROM references_tables.afad;
    DELETE FROM references_tables.amino_acids;
    DELETE FROM references_tables.analysis_groups;
    DELETE FROM references_tables.analysis_lab;
    DELETE FROM references_tables.analysis_matching_groups;
    DELETE FROM references_tables.analysis_modes;
    DELETE FROM references_tables.analysis_replicate;
    DELETE FROM references_tables.analysis_sample_description;
    DELETE FROM references_tables.analysis_types;
    DELETE FROM references_tables.atresia;
    DELETE FROM references_tables.crm;
    DELETE FROM references_tables.derivatization_mode;
    DELETE FROM references_tables.drying_mode;
    DELETE FROM references_tables.extraction_mode;
    DELETE FROM references_tables.fatty_acids;
    DELETE FROM references_tables.fishing_mode;
    DELETE FROM references_tables.gear;
    DELETE FROM references_tables.grinding_mode;
    DELETE FROM references_tables.landing;
    DELETE FROM references_tables.macro_maturity;
    DELETE FROM references_tables.micro_maturity_stage;
    DELETE FROM references_tables.minerals;
    DELETE FROM references_tables.ocean;
    DELETE FROM references_tables.operator;
    DELETE FROM references_tables.organic_contaminants;
    DELETE FROM references_tables.otolith_measurement_type;
    DELETE FROM references_tables.packaging;
    DELETE FROM references_tables.pof;
    DELETE FROM references_tables.prey_groups;
    DELETE FROM references_tables.processing_replicates;
    DELETE FROM references_tables.project;
    DELETE FROM references_tables.sample_position;
    DELETE FROM references_tables.sampling_platform;
    DELETE FROM references_tables.sex;
    DELETE FROM references_tables.species;
    DELETE FROM references_tables.stomach_fullness;
    DELETE FROM references_tables.storage_mode;
    DELETE FROM references_tables.tissue;
    DELETE FROM references_tables.vessel;
    DELETE FROM references_tables.vessel_storage;